server:
    port: 8888
    session:
        timeout: 3600
    tomcat:
        remote-ip-header: x-forwarded-for
        uri-encoding: UTF-8
error:
    whitelabel:
        enabled: false
spring:
    application:
        name: Hector
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/testdb?useUnicode=true&characterEncoding=utf-8
        username: root
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver
        max-active: 50
        max-idle: 20
        min-idle: 10
        initial-size: 5
        validation-query: select 1
        test-on-borrow: true
        test-on-return: false
        test-while-idle: true
        time-between-eviction-runs-millis: 120000
        min-evictable-idle-time-millis: 20
        max-wait: 30000
    activemq:
      broker-url: tcp://192.168.10.5:61616
    http:
        encoding:
            charset: UTF-8
            enabled: true
            force: true
    jpa:
        hibernate:
            naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
        database: mysql
        generate-ddl: true
        show-sql: false
    messages:
        basename: config/message
        cache-seconds: -1
        encoding: UTF-8
    mvc:
        favicon:
            enabled: true
    freemarker:
            cache: false
            enabled: true
            charset: UTF-8
            settings:
                number_format: '#.##'
                datetime_format: yyyy-MM-dd HH:mm:ss
                classic_compatible: true
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss

mybatis:
    mapper-locations: classpath:mybatis/**/*.xml
    type-aliases-package: com.yafeichen.model

banner:
    location: /config/banner.txt

kaptcha:
    fontColor: black
    charSpace: 5
    backGround: white

multipart:
  max-file-size: 20MB
  max-request-size: 20MB





